confirm_os_window_close 0

cursor_trail 100
cursor_trail_decay 0.1 0.4

shell_integration  enabled no-cursor
cursor_shape       block

background_opacity 0.50
background_blur 1

window_padding_width 7
